//
// Created by nerea on 18/10/2023.
//

#ifndef COLECCIONEJERCICIOSNOCIONESCLAVE1_PERSONA_H
#define COLECCIONEJERCICIOSNOCIONESCLAVE1_PERSONA_H


class Persona {

};


#endif //COLECCIONEJERCICIOSNOCIONESCLAVE1_PERSONA_H
